name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to AIS project
    steps:
    - name: Assign NEW issues 
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/Australian-Imaging-Service/projects/2'

    - name: Assign issues `Iteration` in label to "Todo"
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'Iteration')
        && github.event.issue.column_name == ''
      with:
        project: 'https://github.com/orgs/Australian-Imaging-Service/projects/2'
        column_name: 'Todo'
