name: Auto Assign to AIS Project

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to the AIS project
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/Australian-Imaging-Service/projects/2
          github-token: ${{ secrets.AIS_ADMIN_KEY }}
