name: Auto Assign to AIS Project

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to AIS project
    steps:
    - name: Assign issues AIS project backlog
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/orgs/Australian-Imaging-Service/projects/2'
        column_name: 'Backlog'
