name: "Issue matrix"
on:
  issues:
    types: [opened, reopened, closed, edited]
jobs:
  initalise-epic:
    strategy:
        matrix:
          listtype: [Features, Stories]
    if: startsWith(github.event.issue.title, '[EPIC]')
    uses: ./.github/workflows/initialise-issue.yml
    with:
      issuetype: Epic
      listtype: ${{ matrix.listtype }}
  initalise-feature:
    if: startsWith(github.event.issue.title, '[FEATURE]')
    uses: ./.github/workflows/initialise-issue.yml
    with:
      issuetype: Feature
      listtype: Stories
  populate-features:
    if: startsWith(github.event.issue.title, '[FEATURE]')
    uses: ./.github/workflows/populate-issue.yml
    with:
      issuetype: Epic
      listtype: Features
  populate-stories:
    strategy:
        matrix:
          issuetype: [Epic, Feature]
    if: startsWith(github.event.issue.title, '[STORY]')
    uses: ./.github/workflows/populate-issue.yml
    with:
      issuetype: ${{ matrix.issuetype }}
      listtype: Stories
