# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build release

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering by a user with write access to this repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unset header
        # checkout@v2 adds a header that makes branch protection report errors
        # because the Github action bot is not a collaborator on the repo
      run: git config --local --unset http.https://github.com/.extraheader

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Update build tools
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build container images
      run: BUILT_IMAGES=$(arcana deploy xnat build ./pipeline-specs australianimagingservice --registry ghcr.io --license-dir ./licenses  --logfile )

    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }} # - must be in GitHub Secrets!

    # - uses: docker/login-action@v1
    #   with:
    #     registry: index.docker.io
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ ssecrets.DOCKERHUB_PASSWORD }} # - must be in GitHub Secrets!

    # - name: Security scan images
    #   run: for tag=$(arcana deploy list-images $BUILD_TARGETS); do docker scan $tag; done

    - name: Push images to registry
      run: for tag=$(arcana deploy list-images $BUILD_TARGETS); do docker push $tag; done
